version: '3.3'

services:
    phhhp:
        platform: linux/arm64/v8
        env_file: ./.env
        build:
            context: '.'
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
    db:
        image: mariadb:10.5
        volumes:
            - /var/MariaDB:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_DATABASE: mariadb
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
